name: Accessibility Tests (pa11y)

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Building site and running accessibility tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup Node
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install Yarn
        run: npm install -g yarn
      
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build Next App
        run: yarn build

      - name: Boot Next App
        run: yarn start

      - name: Run pa11y-ci
        run: yarn pa11y-ci:sitemap 2>&1 | tee pa11y_output.txt

      - name: Read pa11y_output
        id: pa11y_output
        uses: juliangruber/read-file-action@v1
        with:
          path: ./pa11y_output.txt

      - name: Check for Failures
        if: contains(steps.pa11y_output.outputs.content, 'errno 2')
        run: |
          echo "::error::The site is failing accessibility tests."
          exit 1